#!/usr/bin/env python
"""Export the skymap information from /repo/dc2 so that we can import it into
the preloaded repo here.
This is necessary for ingesting the templates, since at the time we did this,
the template files did not exist in /repo/dc2, just the registry entries.
"""
import os.path
import lsst.daf.butler

SCRIPT_DIR = os.path.abspath(os.path.dirname(__file__))
filename = os.path.join(SCRIPT_DIR, "../etc/skymaps.yaml")

butler = lsst.daf.butler.Butler("/repo/dc2")
with butler.export(filename=filename) as export:
    export.saveDatasets(butler.registry.queryDatasets(collections='skymaps',
                                                      datasetType='skyMap',
                                                      where="skymap='DC2'"))
    export.saveDataIds(
        butler.registry.queryDataIds(
            ["patch"],
            where="tract=4431 AND skymap='DC2'"
        ).expanded()
    )

# Note where the export file came from by prepending a header.
with open(filename, 'r') as input:
    contents = input.read()

with open(filename, 'w') as output:
    output.write("# Export of DC2 skymap for tract=4431\n")
    output.write("# Generated by scripts/export_skymaps.py\n")
    output.write(contents)
